import type { Metadata } from 'next'
import Link from "next/link";

export const metadata: Metadata = {
  title: 'api-mock',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
      <>
          <p className={`font-bold text-center`}>API-MOCK TEST</p>
          <div className={`grid grid-cols-4 p-10 border-gray-400 border-2 h-svh`}>
              <div className={`flex flex-col`}>
                  <Link href={'/api-mock'}>LIST</Link>
                  <Link href={'/api-mock/write'}>WRITE</Link>
              </div>
              <div className={`col-span-3`}>
                  {children}
              </div>
          </div>
      </>
  );
}
