import Link from "next/link";
import Image from "next/image";
import {ResolvingMetadata} from "next";
import type { Metadata } from 'next'

async function getMovie(id:string) {
    const data = await fetch(process.env.PUB_URL + `/api/movie/detail?id=${id}`).then(response => response.json());

    return data;
}

type Props = {
    params: { id: string }
    searchParams: { title: string }
}

//https://nextjs.org/docs/app/building-your-application/optimizing/metadata
export async function generateMetadata({ params, searchParams }: Props, parent: ResolvingMetadata): Promise<Metadata> {
    return {
        title: searchParams.title,
        description: 'Generated by create next app',
    }
}

export default async function detail(context:any, params:any) {
    const {original_title,poster_path,overview} = await getMovie(context.params.id);

    return (
        <div>
            <div className={`p-10`}>
                <h2 className={`text-center font-bold`}>{original_title}</h2>
                <Image src={`https://image.tmdb.org/t/p/w500${poster_path}`} className={`mx-auto`} alt={original_title} width={300} height={300}/>
                <p>{overview}</p>
            </div>

            <Link href={`/movie`} className={`p-3 bg-amber-300 rounded`}>list</Link>
        </div>
    );
}