import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from "@/app/_components/Nav";
import Footer from "@/app/_components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <div className="min-h-screen">
          <Nav/>
          <div className='p-5 container mx-auto mb-auto'>
              <div className={`mt-20`}>
                  {children}
              </div>
          </div>
          <div className={`sticky top-[100vh]`}>
            <Footer/>
          </div>
      </div>
          {/*<style jsx global>{`
        .btn-yellow{
          color:yellow
        }
      `}</style>*/}
      </body>
      </html>
)
}
